[toolchain]
package_manager = "yarn"

[features]
resolution = true
skip-lint = false

[programs.localnet]
achor_core_staking = "9m3z4tmv8ubdZ4syqyztueqhCTUyfsebfwEmwSQXi4c1"

[provider]
cluster = "localnet"
wallet = "~/.config/solana/id.json"

[scripts]
test = "cargo test"

[hooks]
